apiVersion: v1
kind: ConfigMap
metadata:
  name: rickroll-nginx-config
  labels:
    app: rickroll
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        
        location / {
            return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
        }
        
        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
