apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rickroll

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: rickroll
  app.kubernetes.io/instance: rickroll-christmas
